---
- ansible.builtin.include_tasks: os-vars.yml
  tags:
    - fcrepo-syn
    - fcrepo-syn-config
    - fcrepo-syn-install

- ansible.builtin.include_tasks: install.yml
  tags:
    - fcrepo-syn
    - fcrepo-syn-install

- ansible.builtin.include_tasks: "config-{{ ansible_os_family }}.yml"
  tags:
    - fcrepo-syn
    - fcrepo-syn-config
